### ISSUE TITLE
analyze doesn't work with python 3.9.5, incomplatible jiwer library?

### ISSUE THREAD

**Issue by tnixa** [IBM/watson-stt-wer-python#39]
I have python 3.9.5 and i installed the libraries via `pip3 install -r requirements.txt` and have the following libraries:
```
[I] ➜ pip3 list
Package            Version
------------------ ---------
appnope            0.1.2
backcall           0.2.0
certifi            2021.5.30
charset-normalizer 2.0.4
click              8.1.2
configparser       5.2.0
debugpy            1.5.1
decorator          5.1.0
entrypoints        0.3
future             0.18.2
ibm-cloud-sdk-core 3.15.0
ibm-watson         5.3.1
idna               3.2
ipykernel          6.5.0
ipython            7.29.0
jedi               0.18.0
jiwer              2.3.0
joblib             1.1.0
junitparser        1.6.2
jupyter-client     7.0.6
jupyter-core       4.9.1
matplotlib-inline  0.1.3
nest-asyncio       1.5.1
nltk               3.7
numpy              1.21.4
pandas             1.4.2
parso              0.8.2
pexpect            4.8.0
pickleshare        0.7.5
pip                22.0.4
prompt-toolkit     3.0.22
ptyprocess         0.7.0
Pygments           2.10.0
PyJWT              2.3.0
python-dateutil    2.8.2
python-Levenshtein 0.12.2
pytz               2022.1
PyYAML             6.0
pyzmq              22.3.0
regex              2022.3.15
requests           2.26.0
ruamel.yaml        0.17.20
ruamel.yaml.clib   0.2.6
scikit-learn       1.0.1
scipy              1.7.2
setuptools         56.0.0
six                1.16.0
threadpoolctl      3.0.0
tornado            6.1
tqdm               4.64.0
traitlets          5.1.1
urllib3            1.26.6
wcwidth            0.2.5
websocket-client   1.1.0
wheel              0.36.2
```

When I try the `analyze.py` script I am getting the following error which looks to be an incompatible jiwer library:
```
[I] ➜ python3 analyze.py
Using default config filename: config.ini.
cleaned_ref:
[['i', 'will', 'prescribe', 'you', 'some', 'vicodin']]
cleaned_hyp
[['i', 'will', 'prescribe', 'you', 'some', 'vicating']]
Traceback (most recent call last):
  File "/Users/tnixa/watson/sandbox/python-virtual-environments/watson-stt-wer-python/analyze.py", line 258, in <module>
    main()
  File "/Users/tnixa/watson/sandbox/python-virtual-environments/watson-stt-wer-python/analyze.py", line 252, in main
    results = analyzer.analyze()
  File "/Users/tnixa/watson/sandbox/python-virtual-environments/watson-stt-wer-python/analyze.py", line 216, in analyze
    measures = jiwer.compute_measures(cleaned_ref, cleaned_hyp)
  File "/usr/local/lib/python3.9/site-packages/jiwer/measures.py", line 209, in compute_measures
    truth, hypothesis = _preprocess(
  File "/usr/local/lib/python3.9/site-packages/jiwer/measures.py", line 321, in _preprocess
    transformed_truth = truth_transform(truth)
  File "/usr/local/lib/python3.9/site-packages/jiwer/transforms.py", line 76, in __call__
    text = tr(text)
  File "/usr/local/lib/python3.9/site-packages/jiwer/transforms.py", line 55, in __call__
    return self.process_list(sentences)
  File "/usr/local/lib/python3.9/site-packages/jiwer/transforms.py", line 202, in process_list
    return [self.process_string(s) for s in inp]
  File "/usr/local/lib/python3.9/site-packages/jiwer/transforms.py", line 202, in <listcomp>
    return [self.process_string(s) for s in inp]
  File "/usr/local/lib/python3.9/site-packages/jiwer/transforms.py", line 199, in process_string
    return re.sub(r"\s\s+", " ", s)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

**Comment by andrewrfreed** [comment]
Merged in #42
