### ISSUE TITLE
Bug: Multiple errors when executing the script following the example installation

### ISSUE THREAD

**Issue by tbrodbeck** [IBM/watson-stt-wer-python#73]
Hi. We were seeing the following errors:
```
➜  watson-stt-wer-python git:(main) python transcribe.py --config_file config.ini --log_level DEBUG
2023-02-06 14:28:42,672 - DEBUG - Using config file:config.ini
2023-02-06 14:28:42,673 - DEBUG - Transcribing file: sample-files/reference_transcriptions.csv
2023-02-06 14:28:42,673 - ERROR - Error transcribing sample-files/reference_transcriptions.csv:
Traceback (most recent call last):
  File "/Users/t/dev/ibm/speech-to-text-assets/watson-stt-wer-python/transcribe.py", line 143, in transcribe
    self.STT.recognize_using_websocket(audio=AudioSource(audio_file),
  File "/opt/homebrew/lib/python3.10/site-packages/ibm_watson/speech_to_text_v1_adapter.py", line 319, in recognize_using_websocket
    raise ValueError('content_type must be provided')
ValueError: content_type must be provided
2023-02-06 14:28:42,674 - DEBUG - Transcribing file: sample-files/wer_summary.json
2023-02-06 14:28:42,674 - ERROR - Error transcribing sample-files/wer_summary.json:
Traceback (most recent call last):
  File "/Users/t/dev/ibm/speech-to-text-assets/watson-stt-wer-python/transcribe.py", line 143, in transcribe
    self.STT.recognize_using_websocket(audio=AudioSource(audio_file),
  File "/opt/homebrew/lib/python3.10/site-packages/ibm_watson/speech_to_text_v1_adapter.py", line 319, in recognize_using_websocket
    raise ValueError('content_type must be provided')
ValueError: content_type must be provided
2023-02-06 14:28:42,674 - DEBUG - Transcribing file: sample-files/lipitor.wav
2023-02-06 14:28:42,684 - DEBUG - Starting new HTTPS connection (1): iam.cloud.ibm.com:443
2023-02-06 14:28:43,011 - DEBUG - https://iam.cloud.ibm.com:443 "POST /identity/token HTTP/1.1" 200 1146
2023-02-06 14:28:43,012 - ERROR - sample-files/lipitor.wav - Recognize Error received: scheme hwss is invalid
2023-02-06 14:28:43,013 - ERROR - error from callback <bound method RecognizeListener.on_close of <ibm_watson.websocket.recognize_listener.RecognizeListener object at 0x115485ed0>>: RecognizeListener.on_close() takes 2 positional arguments but 4 were given
  File "/opt/homebrew/lib/python3.10/site-packages/websocket/_app.py", line 407, in _callback
    callback(self, *args)
[...]
```
Systems that this was tested on:
```
OS: macOS 13.1 22C65 arm64
Host: MacBookPro18,1
Kernel: 22.2.0
Uptime: 26 days, 23 hours, 7 mins
Packages: 216 (brew)
Shell: zsh 5.8.1
Resolution: 2056x1329, 1920x1080
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Light)
Terminal: iTerm2
Terminal Font: HackNerdFontComplete-Regular 12
CPU: Apple M1 Pro
GPU: Apple M1 Pro
Memory: 3371MiB / 16384MiB

Python 3.10.9
```
&
```
OS: macOS 13.1 22C65 x86_64
Host: MacBookPro16,1
Kernel: 22.2.0
Uptime: 21 days, 6 hours, 9 mins
Packages: 125 (brew)
Shell: zsh 5.8.1
Resolution: 1792x1120@2x
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Dark)
Terminal: vscode
CPU: Intel i9-9980HK (16) @ 2.40GHz
GPU: Intel UHD Graphics 630, AMD Radeon Pro 5300M
Memory: 19447MiB / 32768MiB

Python 3.9.7
```

**Comment by andrewrfreed** [comment]
Thanks for the very clear report @tbrodbeck!

Can you please check the url , it looks like there might be a typo in the url around the scheme `hwss`:
> 2023-02-06 14:28:43,012 - ERROR - sample-files/lipitor.wav - Recognize Error received: scheme hwss is invalid

**Comment by tbrodbeck** [comment]
Ok I did. Both errors can now be fixed: It was (`service_url=hhttps://api.eu-de.speech-to-text.watson.cloud.ibm.com/instances/1ccf61f9-f267-4f60-b308-bc42f9a54198`)
